### PR TITLE
Fixed wrongfull error message

### PR DESCRIPTION
**Pull request by Froelund**
Include ability to create notification with template_id.

### CODE REVIEW

**Comment by SeVeNDuS** [comment]
Hi Froelund,

First of all sorry for my late reply. 
I have double checked [OneSignal Documentation](https://documentation.onesignal.com/docs/notifications-create-notification) and template_id is not required so cannot be require in the nodejs api client

Other possibility is to add a extra parameter with a custom validator

Regards

**Comment by Froelund** [comment]
As I read the documentation, either template_id or contents is required.

**Comment by SeVeNDuS** [comment]
Please, send me the information when you have seen that template_id is required due to in the official link https://documentation.onesignal.com/docs/notifications-create-notification it appears optional

Regards

**Comment by SeVeNDuS** [comment]
I have double read the documentation and the logic is the following:

contents is required unless content_available, _background_data or template_id (one of them) are set.

So template_id not is required but the logic must be changed to validate those parameters

**Comment by SeVeNDuS** [comment]
Now contents is only required if template_ir or content_availabe are not present into params objtect

**Pull request closed without merging**
